#!/bin/bash

while true; do
	if read -a cmd; then

		if [ "$cmd" = 'exit' ]; then
			exit
		fi

		if [ "$cmd" = 'move' ]; then
			position=${cmd[1]}
			move=${cmd[2]}
			~/bin/brd "$(tr _ ' ' <<<$position)" <<<"$move" | tr ' ' _
		fi
	fi
done




