#!/bin/bash

graph=$1
graph=$(realpath $graph)
mkdir -p $graph
flip_file=$2
disp_lock=$3

tmp=~/.config/wrm/tmp/$$
mkdir -p $tmp
tree=$tmp/tree
tmptree=$tmp/tmptree
touch $tree
touch $tmptree
trap "rm -r $tmp" EXIT

read #burn first line

while read input; do
	while ! mkdir $disp_lock 2>/dev/null; do
		sleep 0.2
	done
	tput cup 0 0
	printf '\n'
	if [ -f "$flip_file" ]; then
		board <<<"$input" | flip | border | center
	else
		board <<<"$input" | border | center
	fi
	printf '\n'
	line=$(cut -d':' -f3 <<<$input)
	depth=$(cut -d':' -f4 <<<$input)
	cut -d':' -f2 <<<$input | ./strip | tr '/' '\n' | sed '$ d' >$tmptree
	if ! diff $tree $tmptree >/dev/null; then
		cp $tmptree $tree
		tput ed
	fi
	tree_width=$(gwc -L <$tree) # not portable
	splay $line $depth  <$tree | center $tree_width
	echo;echo
	key=$(cut -d':' -f1 <<<$input | sed 's/\///g' | sed 's/_//' | cut -d'_' -f1)
	tput ed
	if [ -f $graph/$key ]; then
		cat $graph/$key | center
	fi

	rm -r $disp_lock &2>/dev/null
done

