#!/bin/bash

mode_ptr=$1
graph=$2
graph=$(realpath $graph)
mkdir -p $graph

read #burn first line?

while read input; do
    cut -d' ' -f1 <<<"$input" | brd 'set' 'wrm'
	tput cup 0 0
    mode=$(cat $mode_ptr)
    if [ "$mode" == 'tree' ]; then
        printf '\n'; printf '\n'; printf '\n'; printf '\n'
        line=$(cut -d' ' -f2 <<<$input)
        clock=$(cut -d' ' -f3 <<<$input)
        cut -d' ' -f4 <<<$input | tr , '\n' | cut -d'_' -f7 | tr '\n' ' ' | sed 's/\] /\]/g' | tr ']' '\n' | splay $line $clock

    elif [ "$mode" == 'comment' ]; then
        clear
        key=$(cut -d' ' -f1 <<<$input | sed 's/\///g' | sed 's/_//' | cut -d'_' -f1)
        if [ -f $graph/$key ]; then
            printf '\n'; printf '\n'
            cat $graph/$key | center
        fi
    else
        brd show wrm
    fi
done

