#!/bin/bash

config="$HOME/.config/brd"
mkdir -p $config

touch "$config/id"
touch "$config/host"
touch "$config/display"

id=$(cat $config/id)
host=$(cat $config/host)
display=$(cat $config/display)
display=${display:-cat}

cmd=${1:-get}; shift

# local command
if [ "$cmd" == 'set' ]; then
	pair=$1; shift
	key=$(cut -d= -f1 <<<$pair)
	val=$(cut -d= -f2 <<<$pair)
	echo $val >$config/$key
	exit
fi

if [ "$host" == '' ]; then
	echo "ERROR: missing hostname -- $0 set host=[hostname]" >&2
	exit 1
elif [ "$id" == '' ]; then
	echo "ERROR: missing brd id -- $0 set id=[id]" >&2
	exit 1
fi

# remote commands
if [ "$cmd" == 'get' ]; then
	nc $host $id | tail -n1 | $display
elif [ "$cmd" == 'move' ]; then
	move="$@"
	if [ "$move" == '' ]; then
		echo 'ERROR: no move provided' >&2
		exit 1
	fi
	nc $host 1234 <<<"$id $move"
	nc $host $id | tail -n1 | $display
elif [ "$cmd" == 'who' ]; then
	nc $host $id | tail -n1 | grep >/dev/null 'w' && echo 'white' || echo 'black'
elif [ "$cmd" == 'tail' ]; then
	nc $host $id | tail -n2 | head -n1
elif [ "$cmd" == 'cat' ]; then
	nc $host $id | sed '$ d'
else
	echo 'ERROR: command not recognized' >&2
	exit 1
fi
